class trans_fifo;

    // Inputs (generated by TB)
    bit         FClrN;
    bit         FInN;
    bit         FOutN;
    rand bit [31:0] Data_In;

    // Outputs (captured from DUT)
    logic [31:0] F_Data;
    logic        F_EmptyN;
    logic        F_FirstN;
    logic        F_SLastN;
    logic        F_LastN;
    logic        F_FullN;

endclass